name: Prepare semantic release

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  attestations: write
  contents: write
  id-token: write
  issues: write
  pull-requests: write

concurrency:
  group: release-please-main
  cancel-in-progress: true

jobs:
  release-please:
    name: Update release pull request
    runs-on: ubuntu-24.04
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
      tag-name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: Prepare version or release
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  publish:
    name: Build released version
    needs: release-please
    if: needs.release-please.outputs.release-created == 'true'
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ needs.release-please.outputs.tag-name }}
    secrets: inherit
